### PR TITLE
Update Swift-RAC-Macros.podspec

### PR DESCRIPTION
**Pull request by mbogh**
We could also just do:

```
s.dependency "ReactiveCocoa"
```

Issue #4

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hmm. Yeah, we want people using either 2.x or 3.x, but not 1.x or 4.x. @orta is there an operator for this case?

**Comment by orta** [comment]
@segiddins will know this, I don't see any mentions in the guides. I'm willing to say _less than 4_ is reasonable, I bet old 1.x branches won't compile to frameworks.

**Comment by segiddins** [comment]
@ashfurrow `'>= 2.0', '< 4.0'`

**Comment by mbogh** [comment]
@ashfurrow everything a okay?

**Comment by ashfurrow** [comment]
Cooooool I'll push to trunk later; you can use it now though.

**Comment by mbogh** [comment]
wub wub

**Comment by mbogh** [comment]
I'll buy you a Mate at UIKonf :+1:

**Comment by ashfurrow** [comment]
Not at all! I'd love to meet – my [plans are online](https://github.com/ashfurrow/EuroTrip-2015), so if I'm around, let me know 👍

**Pull request merged**
