### PR TITLE
Make sure this pod is usable for both iOS and OSX

### PR DESCRIPTION
**Pull request by iamDecode**
Seemed there was a restriction for iOS for no reason ;)

### CODE REVIEW

**Comment by ashfurrow** [comment]
Good thing @kylef sent me a TapTalk – forgot to watch my own repo :)

**Comment by ashfurrow** [comment]
I'll release an 0.3 version (on trunk) after lunch.

**Comment by kylef** [comment]
Thanks @ashfurrow :heart:

**Comment by kylef** [comment]
Means you probably missed this one too: https://github.com/ashfurrow/Swift-RAC-Macros/issues/1

**Comment by ashfurrow** [comment]
Correct. 

```
[!] The platform of the target `Pods` (OS X 10.9) is not compatible with `ReactiveCocoa (3.0.0-alpha.1)` which has a minimum requirement of iOS 8.0 - OS X 10.10.
```

Oops. I'll get on that, too.

**Comment by ashfurrow** [comment]
I've opened a PR (noted above) to lower the requirement for OS X to 10.9.

**Comment by ashfurrow** [comment]
```
[!] The platform of the target `Pods` (OS X 10.9) is not compatible with `LlamaKit (0.1.1)` which has a minimum requirement of iOS 8.0 - OS X 10.10.
```

I'll be right back.

**Pull request merged**
